# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11-dev", "pypy3.7", "pypy3.8", "pypy3.9"]
        pytest-version: ["7.1.0", "6.0.0", "5.1.0"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
  
    - run: |
        pytest tests -v -m "not testfail"
      name: 'pytest with defaults - passes'
    
    - run: |
        pip install pytest-cov
        pytest tests -v -m "not testfail" --cov --cov-report=html
      name: 'pytest with coverage plugin'

    - run: |
        pip install pytest-xdist
        pytest tests -x --numprocesses=2 -v -m "not testfail" --cov --cov-report=html
      name: 'pytest with xdist plugin'

    - run: |
        pytest tests -v -m "testfail"
      name: 'pytest - failures'
      continue-on-error: true

    - run: |
        pytest tests -v -m "not testfail" --doctest-modules
      name: 'pytest with doctest modules flag - doctest fails'
      continue-on-error: true

